### ISSUE TITLE
Helm install fails

### ISSUE THREAD

**Issue by UlTriX** [teamhephy/workflow#112]
Trying to install on minikube

helm install hephy/workflow --namespace deis --set global.use_rbac=true,router.host_port.enabled=true

returns

Error: must either provide a name or specify --generate-name

Adding the --generate-name

Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]

deis v2.20.0
kubectl
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
helm version
.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Comment by Cryptophobia** [comment]
Thank you for opening the issue @UlTriX 

You are trying to deploy latest hephy workflow on kubernetes version 1.17.3.

We do not officially support k8s > 1.16.x yet due to api deprecations. In the next few weeks we will finish some work on getting it working on k8s 1.16.x @kingdonb .

Alternatively, in order to test workflow, you can try spinning up a minikube cluster that is at lower than the default version by using this command:

```
minikube start --kubernetes-version v1.15.10
```

**Comment by Cryptophobia** [comment]
This is being worked on and will be completed when we have api deprecation work merged in. https://github.com/teamhephy/controller/pull/110
