### ISSUE TITLE
How to manage application databases with workflow?

### ISSUE THREAD

**Issue by ChillarAnand** [teamhephy/workflow#117]
https://github.com/teamhephy/example-python-django shows how to deploy a Django app with SQLite database. Some other example apps also seem to use SQLite database only.

Is there any documentation on how to set up a Postgres/Mongo database with workflow so that apps can use those databases as well?

**Comment by kingdonb** [comment]
Great question!

Workflow ships with a postgres database component, which is used for the controller state and to coordinate controller activities. It is not recommended for production deployments to overload that postgres with additional clients like application tier consumers; although it can be done with care, it could lead to making your Hephy control plane inaccessible when things go topsy turvy, which is the main reason why the documentation and best practices advice suggest strongly to separate "control plane" and "data plane" in your cluster deployment architecture.

However, at least from my understanding you can use the postgres component as a stand-alone utility, which behaves exactly like the built-in database in the default configuration of Workflow.

This pattern is not well documented, as far as I know, and I have opened an issue teamhephy/postgres#15 to track my thoughts about what content it should have. I made "postgres in standalone mode" the number one point, seems like a good idea for where to start.

Mongodb is not part of our stack and no foreseeable plans to integrate it.

For a really well documented system that does support both of those databases and others, which is meant for use with application workloads and use cases like yours, can certainly be used with applications deployed on Workflow, check out kubedb which I have been using to provide mysql databases. Kubedb supports postgres and mongodb with an operator approach.

**Comment by Cryptophobia** [comment]
Hi @ChillarAnand , easiest path forward to have a standalone database component is to deploy [postgresql](https://github.com/helm/charts/tree/master/stable/postgresql) or [mongodb](https://github.com/helm/charts/tree/master/stable/mongodb) helm charts and manage them inside the k8s cluster separately as separate helm releases. This isolates your application from the data plane. Then have your application use credentials (kubernetes secret or ENV vars) to connect to that database service running inside the cluster.

Most of the example applications do not have reliable databases or use file system database like SQLite because that was easiest way to show the power of Hephy/Deis without having to spin up databases. 

Another route is to deploy a highly-available and isolated database outside your cluster but within your VPC inside your cloud provider AWS /GCE/Azure/DO or whichever DaaS (database as a service) you want to use. This is by far the most reliable way to manage databases because it is managed outside the k8s application cluster and SLAs (service-level agreements) are provided by your cloud provider. 

If you are looking for a non-production solution that is also easy to implement, another solution is to manage database inside the k8s cluster with something like [KubeDB](https://kubedb.com/). 

It really boils down to what kind of application (production/staging/personal) and scale/reliability of the database you are targeting.

**Comment by ChillarAnand** [comment]
Thanks for your insights @kingdonb, @Cryptophobia 
I have set up Postgres/Elasticsearch with KubeDB on AWS EKS for testing and it seems to be working fine for now.

I am planning to set up Postgres & Elasticsearch databases for production. Scaling is not a problem as the workload is less but looking for high reliability.
I am trying to understand if it makes sense to use kubedb(or other solutions to setup DB within k8s) or use cloud provider AWS/RDS for production databases?

**Comment by kingdonb** [comment]
There is really a personal calculus to consider making this decision. There are some factors that can make it simpler, though. You're weighing the risks vs cost, so innate in risk is definitely the question of how much failure you can tolerate, opposite that the question of how much you're meaning to spend in order to mitigate the risks you judge to be the worst out of of those risks.

How much and what kind of failure! Is downtime a scheduled event, or should recovery be verifiable and practiced (once, or on a regular basis)

The postgres database model does a great job of backups, but a backup cannot be said to be any good until you are certain that you can restore it. (Fortunately it's easy to verify this, just `kubectl delete pod deis-database-*` and watch it come back. Of course if you wanted to verify that without nuking the running instance, perhaps a bit harder...)

The best argument for RDS or off-cluster database, I think, is performance – if all stateful components are hosted outside of the cluster, then performance concerns about the database and scaling can be handled totally separately from performance concerns within the cluster.

Also, worth asking how much can you tolerate a cluster-wide outage? And how nervous will you be while waiting to see if that database restores, when it's critical downtime. (You don't need to be nervous about it, when you practice this on a regular basis and know how long it takes. You can also restore the database onto a staging cluster and pivot from one cluster to another, as a way to practice and learn how long restores of the database will take.)

Can you see yourself ever doing this, and does it provide you with enough value to justify the cost of your time? For me, I think the answer is yes, I want to know it works and keep my control over variables, but an objective analysis of the dollar cost of time versus the dollar cost of RDS instance that maybe you can just trust and don't worry, might result in a very different answer.

**Comment by kingdonb** [comment]
Here is a good looking article from `@learnk8s` on Twitter, who are a great learning resource, this note which I've been sitting on in my inbox, seems to have some overlap with this question: 

> Hi there!
> --
> Dan here.
> If you are hosting your cluster in the cloud, you might have had the following questions at least once:
> How do you configure cloud databases and message brokers in Kubernetes (e.g. AWS RDS, Azure SQL, GCP Cloud SQL)?
> Do you create them outside the cluster?
> Perhaps inside the cluster using Custom Resource Definitions (CRDs)?
> I had those questions — and many of our students did too.
> So here is an article that summarises your options:

https://learnk8s.io/cloud-resources-kubernetes

**Comment by ChillarAnand** [comment]
Thanks for the explanation and providing some useful resources.
