### ISSUE TITLE
Is charts/workflow/Chart.yaml still in use?

### ISSUE THREAD

**Issue by ChristianWeissCG** [teamhephy/workflow#92]
I am new to this project trying to understand how it is structured.

Looks like there are still some old references to charts from the deis team:
https://github.com/teamhephy/workflow/blob/master/charts/workflow/requirements.yaml

Do team hephy have a nexus chart repository (or similar)?
https://charts.deis.com seams to be ofline

`helm dep build` is failing 

I also wonder about the version string, so i guess there are some helper script to transform these helm charts into a valid helm chart (that is valid from perspective of `helm lint`). Where do i find the helper scripts?

I am asking because i want to understand the concept of a umbrella helm chart and https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md is referencing deis (/ hephy) as a good example.

**Comment by Cryptophobia** [comment]
Hey @ChristianWeissCG , thank you for your question. Unfortunately, some of our published charts for the individual Hephy components are not always up to date right now. But to get the general idea you can check out our own helm repository of charts `charts.teamhephy.com`.

To add our charts repo:
```
 helm repo add hephy https://charts.teamhephy.com 
```

To get the main chart on your local:
```
 helm fetch hephy/workflow --untar
```
This will create a workflow folder in your current directory. Then you can go inside and explore the main chart and all the charts that depend on it inside in the `../charts` directory. Normally in this workflow folder you can do the command `helm lint` or `helm dep build` but since some of our charts are not up to date on our charts repository this command will not work as helm will complain that it can't find the right versions of the charts in the `charts.teamhephy.com` repo. We have been manually assembling this master umbrella chart and the charts within it so it's not a problem for us. :+1:

**Comment by Cryptophobia** [comment]
Hey, let us know if you have further questions. I'm going to close this now. You can reach us on slack.teamhephy.com (teamhephy.slack.com) or you can open another issue in the future. :)
